### ISSUE TITLE
main-bower-files

### ISSUE THREAD

**Issue by MikaelX** [verlok/picturePolyfill#19]
Hi

Thanks for a great plugin! when i run gulp main-bower-files the picturePolyfill is not included, in the bower.json the main is set to main: "picturePolyfill.js" but this file actually resides inside the src folder.

This means that there is no file copied from the main-bower-file script unless you manually copy or generate the .js file in the ./ directory.

**Comment by verlok** [comment]
Thanks for letting me know. I'm fixing it.

**Comment by verlok** [comment]
Done!

**Comment by MikaelX** [comment]
Awesome :)

Skickat från min iPhone
